
name: tests
on: [push]
jobs:
  macos:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
	with:
		ref: main

    - name: Build
      run: swift build -c debug --build-tests

    - name: Test
      run: swift test -c debug


